#!/usr/bin/bash

script_dir="$(dirname "$(realpath "$0")")"

# Install Neovim and dependencies
packages=(
  neovim
  npm
  nodejs
  python3
  python3-pip
  stow
  pipx
  clang-format
  clangd
  ripgrep
  unzip
)

if ! dpkg -s "${packages[@]}" &> /dev/null; then
  sudo apt-get update && sudo apt-get install -y "${packages[@]}"
else
  echo "All packages are already installed."
fi

sudo pipx install \
  cmake-language-server

# Recursively creates symbolic links to nvim files in ~/ for .config set up
pushd $script_dir
echo "stowing dotfiles..."
stow -t $HOME nvim/
stow -t $HOME tmux/
popd

# Fix permissions
sudo chown -R $(id -u):$(id -g) $HOME/.local/share/


##### BASHRC #####
declare -a ALIASES=(
"alias nv='nvim'"
"alias v='nvim'"
)
bashrc_changed=0

for alias in "${ALIASES[@]}"; do
  if [ $(cat ~/.bashrc | grep "$alias" | wc -l) -eq 0 ]; then
    echo "Adding $alias to ~/.bashrc ..."
    echo $alias >> ~/.bashrc
    bashrc_changed=1
  fi
done

if [ $bashrc_changed -eq 1 ]; then
  echo "~/.bashrc was changed. Remember to run:"
  echo "source ~/.bashrc"
fi
