bind C-s run-shell "~/.local/bin/tmux-session save && tmux display-message 'session saved'"
bind C-r run-shell "~/.local/bin/tmux-session restore"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
set-option -g default-shell /usr/bin/zsh

# https://stackoverflow.com/questions/41783367/tmux-tmux-true-color-is-not-working-properly
set-option -sa terminal-overrides ',xterm*:Tc'
